# ==============================================================================
# 404_Team_not_Found Layer 4 Traffic Gateway Configuration[cite: 1]
# ==============================================================================
# Format:
# [route] defines a new forwarding rule.
# frontend_port: The local TCP port the gateway listens on[cite: 1].
# backend: The target IPv4 address and port to forward traffic to[cite: 1].
# Multiple backends under one route will be used for Round-Robin Load Balancing[cite: 1].
# ==============================================================================

# Route 1: A single-backend proxy rule (Milestone 3 testing)[cite: 1]
[route]
frontend_port = 8080
backend = 127.0.0.1:9001
backend = 127.0.0.1:9002

# Route 2: A multi-backend load balancing rule (Milestone 5 testing)[cite: 1]
[route]
frontend_port = 8888
backend = 127.0.0.1:9003
backend = 127.0.0.1:9004
backend = 127.0.0.1:9005